name = "ClimateTools"
uuid = "4f4ee721-4970-5af2-8560-6c1d960e3231"
authors = ["Philippe Roy <borghor@yahoo.ca>"]
repo = "https://github.com/JuliaClimate/ClimateTools.jl.git"
version = "0.22.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
ClimateBase = "35604d93-0fb8-4872-9436-495b01d137e2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Extremes = "fe3fe864-1b39-11e9-20b8-1f96fa57382d"
GeoStats = "dcc97b0b-8ce5-5539-9008-bb190f959ef6"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
InverseDistanceWeighting = "6a8e3230-34bb-5a86-b9da-9f7447a06da5"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RollingFunctions = "b0e4dd01-7b14-53d8-9b45-175a3e362653"
Shapefile = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ArgCheck = "1, 2.0"
AxisArrays = "0.3, 0.4"
ClimateBase = "0.6"
DataFrames = "0.19, 0.20, 0.21, 0.22"
Distances = "0.7, 0.8, 0.9"
Extremes = "0.1"
GeoStats = "0.11, 0.13, 0.14"
Interpolations = "0.12"
InverseDistanceWeighting = "0.3, 0.4"
IterTools = "1.1, 1.2, 1.3"
NCDatasets = "0.9, 0.10"
NaNMath = "0.3"
NetCDF = "0.7, 0.8, 0.9, 0.10"
Polynomials = "0.5, 0.6, 0.7, 0.8, 1.0"
ProgressMeter = "1"
PyCall = "1.91"
Reexport = "0.2"
RollingFunctions = "0.6"
Shapefile = "0.4, 0.5, 0.6"
julia = "1.2, 1.3, 1.4"
