name = "ClimateTools"
uuid = "4f4ee721-4970-5af2-8560-6c1d960e3231"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
CondaBinDeps = "a9693cdc-2bc8-5703-a9cd-1da358117377"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
# Pkg = "fe1c5a76-5840-53d2-82f9-288dd83ce2ce"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Shapefile = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"
Statistics = "1c261c3c-9a38-5c8c-b229-00278e4435fb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ArgCheck = "≥ 1.0.0"
AxisArrays = "≥ 0.3.0"
BinDeps = "≥ 0.4.0"
Images = "≥ 0.17.3"
Interpolations = "≥ 0.8.0"
IterTools = "≥ 1.1.0"
NCDatasets = "≥ 0.9.2"
NaNMath = "≥ 0.3.2"
NetCDF = "≥ 0.7.1"
Polynomials = "≥ 0.5.1"
ProgressMeter = "≥ 0.6.0"
PyCall = "≥ 1.90.0"
PyPlot = "≥ 2.6.3"
Reexport = "≥ 0.2.0"
Shapefile = "≥ 0.4.0"
julia = "≥ 0.7.0"
